sudo: false
language: bash
os:
  - linux
addons:
  apt:
    packages:
      - gperf
      - python
      - python-serial

before_install:
  # Save path to the git respository
  - export REPO_PATH=$HOME/esp-idf-template/components/WemosMotorShieldESP32
  - export PROJECT_PATH=$HOME/esp-idf-template/
  - git clone https://github.com/espressif/esp-idf-template $HOME/esp-idf-template
  - mkdir -p $HOME/esp-idf-template/components/
  - mv $(pwd) $REPO_PATH
  - rm -rf $HOME/esp-idf-template/main/main.c
  - rm -rf $HOME/esp-idf-template/main/Kconfig.projbuild
  - cp $REPO_PATH/examples/example.cpp $HOME/esp-idf-template/main/main.cpp

install:
  # Install ESP32 toochain following steps as desribed
  # in http://esp-idf.readthedocs.io/en/latest/linux-setup.html
  #
  - mkdir -p $HOME/esp
  - cd ~/esp
  # Get ESP-IDF from github
  - git clone --recursive https://github.com/espressif/esp-idf.git $HOME/esp/esp-idf
  - export IDF_PATH=$HOME/esp/esp-idf
  - pip install --user -r $IDF_PATH/requirements.txt
  - chmod +x $IDF_PATH/install.sh
  - $IDF_PATH/install.sh

script:
  # Go back to the git repository
  - cd $PROJECT_PATH
  - source $IDF_PATH/export.sh
  - sed -i -e 's/main.c/main.cpp/g' ./main/CMakeLists.txt
  - idf.py reconfigure
  - # enable CXX exceptions
  - echo "CONFIG_COMPILER_CXX_EXCEPTIONS=y" >> ./sdkconfig
  - echo "CONFIG_COMPILER_CXX_EXCEPTIONS_EMG_POOL_SIZE=0" >> ./sdkconfig
  - echo "CONFIG_CXX_EXCEPTIONS=y" >> ./sdkconfig
  - echo "CONFIG_CXX_EXCEPTIONS_EMG_POOL_SIZE=0" >> ./sdkconfig
  - idf.py build
